#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if (len(sys.argv) == 2):
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	sessionid = sys.argv[1]
elif (len(sys.argv) == 3):
	path = sys.argv[1]
	sessionid = sys.argv[2]
else:
	print("Usage: %s [modem] <sessionid>" % (sys.argv[0]))
	print("ex. %s 1" % (sys.argv[0]))
	sys.exit(1)

telit = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.TelitMEControl')

try:
	print("Close Logical Channel %s..." % path)
	telit.CloseLogicalChannel(dbus.Int32(sessionid))
except dbus.DBusException as e:
	print("Error Close Logical Channel %s: %s" % (path, str(e)))
	exit(2)

print('')
