#!/usr/bin/python3

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

if (len(sys.argv) == 2):
	modems = manager.GetModems()
	path = modems[0][0]
	num = sys.argv[1]
elif (len(sys.argv) == 3):
	path = sys.argv[1]
	num = sys.argv[2]
else:
	print("Usage: %s [modem] <number>" % (sys.argv[0]))
	sys.exit(1)


mgr = dbus.Interface(bus.get_object('org.ofono', path),
				'org.ofono.VoiceCallManager')

calls = mgr.GetCalls()

for path, properties in calls:
	state = properties["State"]
	print("[ %s ] %s" % (path, state))

#	if state != "incoming":
#		continue


call = dbus.Interface(bus.get_object('org.ofono', path),
				'org.ofono.VoiceCall')

call.Deflect(num)
