#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if (len(sys.argv) == 2):
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	cid = sys.argv[1]
elif (len(sys.argv) == 3):
	path = sys.argv[1]
	cid = sys.argv[2]
else:
	print("Usage: %s [modem] <profile number>" % (sys.argv[0]))
	print("ex. %s 3" % (sys.argv[0]))
	sys.exit(1)

telit = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.TelitDataNetwork')

try:
	print("Delete profile %s..." % path)
	telit.DeleteProfile(dbus.String(cid))
except dbus.DBusException as e:
	print("Error trace %s: %s" % (path, str(e)))
	exit(2)
