#!/usr/bin/python3

import dbus
import sys
import time

bus = dbus.SystemBus()

if len(sys.argv) == 4:
	path = sys.argv[1]
	pin_type = sys.argv[2]
	pin = sys.argv[3]
elif len(sys.argv) == 3:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
					'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	pin_type = sys.argv[1]
	pin = sys.argv[2]
else:
	print("%s [PATH] pin_type pin" % (sys.argv[0]))
	sys.exit(0)

print("Enter Pin for modem %s..." % path)
simmanager = dbus.Interface(bus.get_object('org.ofono', path),
				'org.ofono.SimManager')

try:
	simmanager.EnterPin(pin_type, pin)
except dbus.DBusException as e:
	print("Error PIN %s: %s" % (path, str(e)))

time.sleep(3)

properties=simmanager.GetProperties()

#  remaining entries: dbus.Dictionary({dbus.String('pin'): dbus.Byte(3)}, signature=dbus.Signature('sy'), variant_level=1)
for key in properties.keys():
	if key in ["Retries"]:
		val = ""
		for i in properties[key]:
			val +=  "[" + i + " = "
			val += str(int(properties[key][i])) + "] "
		print("%s: %s" % (key, val))
