#!/usr/bin/python3

import dbus, sys

bus = dbus.SystemBus()

if len(sys.argv) == 2:
        path = sys.argv[1]
else:
        manager = dbus.Interface(bus.get_object('org.ofono', '/'),
                                                'org.ofono.Manager')
        modems = manager.GetModems()
        path = modems[0][0]

network = dbus.Interface(bus.get_object('org.ofono', path),
                                                'org.ofono.NetworkRegistration')

properties = network.GetProperties()

print("Strength: %d" % (properties['Strength']))
