#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 2:
	path = sys.argv[1]
	enabled = sys.argv[2]
elif len(sys.argv) == 1:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
else:
	print("%s [PATH] on/off" % (sys.argv[0]))
	sys.exit(1)

print("Setting delivery report use for modem %s..." % path)
sms = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.MessageManager')

props = sms.GetProperties()

print('')
for key in props.keys():
	val = props[key]
	print("        %s = %s" % (key, val))

print('')
