#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if (len(sys.argv) == 2):
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	dfname = sys.argv[1]
elif (len(sys.argv) == 3):
	path = sys.argv[1]
	dfname = sys.argv[2]
else:
	print("Usage: %s [modem] <dfname>" % (sys.argv[0]))
	print("ex. %s FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" % (sys.argv[0]))
	sys.exit(1)

telit = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.TelitMEControl')

try:
	print("Open Logical Channel %s..." % path)
	sessionid = telit.OpenLogicalChannel(dbus.String(dfname))
except dbus.DBusException as e:
	print("Error Open Logical Channel %s: %s" % (path, str(e)))
	exit(2)

print("Session ID: %d" % sessionid)

print('')
