#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 2:
	path = sys.argv[1]
else:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
			'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]

print("Rebooting modem %s..." % path)
telit = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.TelitTrace')

try:
	telit.Reboot()
except dbus.DBusException as e:
	print("Error rebooting %s: %s" % (path, str(e)))
	exit(2)
