#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if (len(sys.argv) == 2):
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	conf = sys.argv[1]
elif (len(sys.argv) == 3):
	path = sys.argv[1]
	conf = sys.argv[2]
else:
	print("Usage: %s [modem] <config mask (32 byte)>" % (sys.argv[0]))
	print("ex. C80000000080E8FFF7FFFDFFF7FFFFFFFFFFFF7FE8FFFFFF7FC2730E5D44800A")
	print("ex. 000000000080C0FFF7FFFD7FF5FFFFFFFFFFFF7FE0FFFFFF7FC2530E5C44800A")
	print("ex. FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")
	sys.exit(1)

telit = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.TelitTrace')

try:
	print("Set config %s..." % path)
	telit.SetProperty("TraceConfig", dbus.String(conf))
except dbus.DBusException as e:
	print("Error trace %s: %s" % (path, str(e)))
	exit(2)
