#!/usr/bin/python3

import dbus
import sys

if len(sys.argv) < 2:
	print("")
	print("Usage: set-tech-preference <technology> ")
	print("")
	print("The possible values are:")
	print("- \"any\" Radio access technology selection is done automatically, based on reception and availability.")
	print("- \"gsm\" Only GSM used for radio access.")
	print("- \"umts\" Only UMTS used for radio access.")
	print("- \"lte\" Only LTE used for radio access.")
	print("- \"gsm-lte\" GSM or LTE used for radio access.")
	print("- \"gsm-umts\" GSM- UMTS used for radio access.")
	print("- \"umts-lte\" UMTS or LTE used for radio access.")
	print("")
	exit(1)

bus = dbus.SystemBus()

if len(sys.argv) == 3:
	path = sys.argv[1]
	tech = sys.argv[2]
elif len(sys.argv) == 2:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	tech = sys.argv[1]
else:
	print("%s [PATH] technology" % (sys.argv[0]))

print("Setting technology preference for modem %s..." % path)
radiosettings = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.RadioSettings')

radiosettings.SetProperty("TechnologyPreference", tech);
