#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if (len(sys.argv) == 2):
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	conf = sys.argv[1]
elif (len(sys.argv) == 3):
	path = sys.argv[1]
	conf = sys.argv[2]
else:
	print("Usage: %s [modem] [power status (full, airplane, saving)]" % (sys.argv[0]))
	sys.exit(1)

telit = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.TelitPowerManagement')

try:
	print("Setting Power Status %s..." % path)
	telit.SetProperty("PwMgmState", conf)
except dbus.DBusException as e:
	print("Error Power Status %s: %s" % (path, str(e)))
	exit(2)
