#!/usr/bin/python3

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()
path = modems[0][0]

cv = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.CallVolume')


try:
	cv.SetProperty("Muted", dbus.Boolean(int(sys.argv[1])))
except dbus.DBusException as e:
	print("Unable to set property: %s" % e)
	sys.exit(1);

properties = cv.GetProperties()

print("Muted: %s" % (properties["Muted"]))